# Generated by Django 5.2.8 on 2025-11-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data de referência da coleta')),
                ('dominio', models.CharField(max_length=255)),
                ('total_usuarios', models.IntegerField(default=0)),
                ('total_grupos', models.IntegerField(default=0)),
                ('sistemas_risco', models.IntegerField(default=0)),
                ('usuarios_bloqueados', models.IntegerField(default=0)),
                ('grupos_vazios', models.IntegerField(default=0)),
                ('usuarios_azure', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
