# Generated by Django 5.2.8 on 2025-11-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricaseguranca',
            options={'ordering': ['data']},
        ),
        migrations.AddField(
            model_name='metricaseguranca',
            name='contas_admin',
            field=models.IntegerField(default=0, verbose_name='Admins Totais'),
        ),
        migrations.AddField(
            model_name='metricaseguranca',
            name='senhas_nao_expiram',
            field=models.IntegerField(default=0, verbose_name='Senhas que não expiram'),
        ),
        migrations.AddField(
            model_name='metricaseguranca',
            name='usuarios_obsoletos',
            field=models.IntegerField(default=0, verbose_name='Usuários Stale'),
        ),
    ]
